export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";

export const JOIN_COURSE_SUCCESS = "JOIN_COURSE_SUCCESS";
export const JOIN_COURSE_REQUEST = "JOIN_COURSE_REQUEST";
export const JOIN_COURSE_FAIL = "JOIN_COURSE_FAIL";

export const GET_ALL_MEMBER_REQUEST = "GET_ALL_MEMBER_REQUEST";
export const GET_ALL_MEMBER_SUCCESS = "GET_ALL_MEMBER_SUCCESS";
export const GET_ALL_MEMBER_FAIL = "GET_ALL_MEMBER_FAIL";

export const GET_ALL_USER_COURSE_SUCCESS = "GET_ALL_USER_COURSE_SUCCESS"; 
export const GET_ALL_USER_COURSE_FAIL = "GET_ALL_USER_COURSE_FAIL"; 
export const GET_ALL_USER_COURSE_REQUEST = "GET_ALL_USER_COURSE_REQUEST"; 

export const GET_ALL_INFO_COURSE_REQUEST = "GET_ALL_INFO_COURSE_REQUEST";
export const GET_ALL_INFO_COURSE_SUCCESS = "GET_ALL_INFO_COURSE_SUCCESS";
export const GET_ALL_INFO_COURSE_FAIL = "GET_ALL_INFO_COURSE_FAIL";

export const JOIN_COURSE_BY_URL_FAIL = "JOIN_COURSE_BY_URL";
export const JOIN_COURSE_BY_URL_SUCCESS = "JOIN_COURSE_BY_URL_SUCCESS";
export const JOIN_COURSE_BY_URL_REQUEST = "JOIN_COURSE_BY_URL_REQUEST";