export const CREATE_EXERCISE_TYPE_REQUEST = "CREATE_EXERCISE_TYPE_REQUEST";
export const CREATE_EXERCISE_TYPE_SUCCESS = "CREATE_EXERCISE_TYPE_SUCCESS";
export const CREATE_EXERCISE_TYPE_FAIL = "CREATE_EXERCISE_TYPE_FAIL";

export const UPDATE_EXERCISE_TYPE_REQUEST = "UPDATE_EXERCISE_TYPE_REQUEST";
export const UPDATE_EXERCISE_TYPE_SUCCESS = "UPDATE_EXERCISE_TYPE_SUCCESS";
export const UPDATE_EXERCISE_TYPE_FAIL = "UPDATE_EXERCISE_TYPE_FAIL";

export const DELETE_EXERCISE_TYPE_REQUEST = "DELETE_EXERCISE_TYPE_REQUEST";
export const DELETE_EXERCISE_TYPE_SUCCESS = "DELETE_EXERCISE_TYPE_SUCCESS";
export const DELETE_EXERCISE_TYPE_FAIL = "DELETE_EXERCISE_TYPE_FAIL";

export const UPDATE_ORDER_CHANGE_SUCCESS = "UPDATE_ORDER_CHANGE_SUCCESS";