export const UPSERT_STUDENT_ID_REQUEST = "UPSERT_STUDENT_ID_REQUEST";
export const UPSERT_STUDENT_ID_SUCCESS = "UPSERT_STUDENT_ID_SUCCESS";
export const UPSERT_STUDENT_ID_FAIL = "UPSERT_STUDENT_ID_FAIL";

export const GET_ROLE_MEMBER_SUCCESS = "GET_ROLE_MEMBER_SUCCESS";
export const GET_ROLE_MEMBER_FAIL = "GET_ROLE_MEMBER_FAIL";


export const TYPEROLE = {
    TEACHER: "teacher",
    STUDENT: "student",
    ASSISTANT: "assistant"
}