export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAIL = "NOTIFICATION_FAIL";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
export const NOTIFICATION_INFO = "NOTIFICATION_INFO";